services:
  db:
    image: postgres
    restart: always
    container_name: dbPostgres
    secrets:
      - db-password
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "api",
          "-U",
          "postgres"
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    expose:
      - 5432

  adminer:
    image: adminer
    restart: always
    container_name: adminer
    ports:
      - 8080:8080
    networks:
      - backnet

  frontend:
    build:
      context: SOGAP-React
      target: frontend
    container_name: frontend
    restart: always
    command: "npm start --host 0.0.0.0 --port 3000"
    working_dir: /code
    user: "node"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=80
      - NODE_ENV=production
    volumes:
      - ./SOGAP-React:/code:delegated
      - /code/node_modules
    expose:
      - 3000
    networks:
      - backnet


  process-back:
    build:
      context: SOGAP-Process-Service
      target: builder
    working_dir: /code
    restart: always
    container_name: processBack
    volumes:
      - ./SOGAP-Process-Service:/code
    networks:
      - backnet
    expose:
      - 8000
    depends_on:
      db:
        condition: service_healthy

  notification-back:
    build:
      context: SOGAP-Notification-Service
      target: builder
    working_dir: /code
    restart: always
    container_name: notificationBack
    volumes:
      - ./SOGAP-Notification-Service:/code
    networks:
      - backnet
    expose:
      - 8001
    depends_on:
      db:
        condition: service_healthy

  nginx:
    restart: always
    container_name: nginx
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 80:80
      - 8000:8000
    networks:
      - backnet
    depends_on:
      - process-back
      - notification-back
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  db-data:


secrets:
  db-password:
    file: ./db/password.txt

networks:
  backnet:
