services:
  db:
    image: postgres
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backnet
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - 5432:5432
    expose:
      - 5432
  
  adminer:
    image: adminer
    restart: always 
    ports:
      - 8080:8080
    networks:
      - backnet

        


volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
